// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATBrr1du_qr4JdAIegQcU2B1yMjIcRgPY',
    appId: '1:958501398871:web:14425f245ed77c5d06f612',
    messagingSenderId: '958501398871',
    projectId: 'eduquizz-c71ac',
    authDomain: 'eduquizz-c71ac.firebaseapp.com',
    storageBucket: 'eduquizz-c71ac.firebasestorage.app',
    measurementId: 'G-RDFS0DLKKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCglbBC-w1yFN49m2ytdPo8SirZbhy7c6o',
    appId: '1:958501398871:android:d143f0d094eb307506f612',
    messagingSenderId: '958501398871',
    projectId: 'eduquizz-c71ac',
    storageBucket: 'eduquizz-c71ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKzKcmDKPpth5ncC1c1YY18D9wZVMNR5s',
    appId: '1:958501398871:ios:58e4799d7267ea9606f612',
    messagingSenderId: '958501398871',
    projectId: 'eduquizz-c71ac',
    storageBucket: 'eduquizz-c71ac.firebasestorage.app',
    iosClientId: '958501398871-mblsa6td18a5qa0grejr2ng5iq3385f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKzKcmDKPpth5ncC1c1YY18D9wZVMNR5s',
    appId: '1:958501398871:ios:58e4799d7267ea9606f612',
    messagingSenderId: '958501398871',
    projectId: 'eduquizz-c71ac',
    storageBucket: 'eduquizz-c71ac.firebasestorage.app',
    iosClientId: '958501398871-mblsa6td18a5qa0grejr2ng5iq3385f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATBrr1du_qr4JdAIegQcU2B1yMjIcRgPY',
    appId: '1:958501398871:web:e169356a105dc3b006f612',
    messagingSenderId: '958501398871',
    projectId: 'eduquizz-c71ac',
    authDomain: 'eduquizz-c71ac.firebaseapp.com',
    storageBucket: 'eduquizz-c71ac.firebasestorage.app',
    measurementId: 'G-M2ZPMHC566',
  );
}
